version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-23-191-123.compute-1.amazonaws.com
            port: '5432'
            database: dbo0qs8gpfhghr
            ssl: true
            user: nnhqmblrtkgelz
            password: 44f94f83c2ecf7698f6929f39166df07e496687e06b2c322e454ac4fd3b01098
            migrations: true